server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: avocado-api
  graphql:
    path: /graphql
    graphiql:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/tiashackinterface
    username: tia
    password: temppass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      data-source-properties:
        cachePrepStmts: false       # Disable prepared statement caching
        useServerPrepStmts: false  # Avoid server-side prepared statements
        prepStmtCacheSize: 250     # (Optional) Limit the cache size
        prepStmtCacheSqlLimit: 2048 # (Optional) Limit SQL string length
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG
