server:
  port: 8080
spring:
  application:
    name: avocado-api
  graphql:
    path: /api/graphql
    graphiql:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/tiashackinterface
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
